name: Build frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend/
        run: npm install

      - name: Build
        working-directory: frontend/
        run: npm run build

#      - name: Lint
#        working-directory: frontend/
#        run: npm run lint

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: spoud/toeggelomat-frontend:latest
