name: Build backend

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    paths: ['backend/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with maven
        working-directory: backend/
        run: mvn -B clean package -Pnative
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: backend/
          file: backend/src/main/docker/Dockerfile.native-micro
          push: true
          tags: spoud/toeggelomat-backend:latest

      - name: Build and push tag
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: backend/
          file: backend/src/main/docker/Dockerfile.native-micro
          push: true
          tags: spoud/toeggelomat-backend:${{  github.ref_name }}
